#import "Notti.h"
#import "Notti-Swift.h" // auto-generated by Xcode/CocoaPods for this pod's Swift sources (T2 spike, AD-002)

@implementation Notti {
    NottiImpl *_impl;
}

- (instancetype)init {
    if (self = [super init]) {
        _impl = [NottiImpl new];

        __weak Notti *weakSelf = self;
        _impl.emitReceivedHandler = ^(NSDictionary *payload) {
            [weakSelf emitOnNotificationReceived:payload];
        };
        _impl.emitClickedHandler = ^(NSDictionary *payload) {
            [weakSelf emitOnNotificationClicked:payload];
        };
    }
    return self;
}

- (void)initialize:(NSString *)appId
         clientKey:(NSString *)clientKey
           baseUrl:(NSString *)baseUrl
{
    [_impl initialize:appId clientKey:clientKey baseUrl:baseUrl];
}

- (void)requestPermission:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject
{
    [_impl requestPermission:^(NSNumber *granted) {
        resolve(granted);
    }];
}

- (void)login:(NSString *)externalUserId
{
    [_impl login:externalUserId];
}

- (void)logout
{
    [_impl logout];
}

- (void)addTags:(NSDictionary *)tags
{
    [_impl addTags:tags];
}

- (void)removeTags:(NSArray *)keys
{
    [_impl removeTags:keys];
}

- (void)setSubscription:(BOOL)enabled
{
    [_impl setSubscription:enabled];
}

- (void)getInitialNotificationClick:(RCTPromiseResolveBlock)resolve
                             reject:(RCTPromiseRejectBlock)reject
{
    // Resolves the cold-start tap once, then null. NSNull keeps the JS side on
    // the Spec's `NotificationPayload | null` - resolve(nil) would hand JS
    // `undefined` instead.
    NSDictionary *payload = [_impl takeInitialNotificationClick];
    resolve(payload ?: (id)[NSNull null]);
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<facebook::react::NativeNottiSpecJSI>(params);
}

+ (NSString *)moduleName
{
  return @"Notti";
}

@end
