#import "Nuntis.h"
#import "Nuntis-Swift.h" // auto-generated by Xcode/CocoaPods for this pod's Swift sources (T2 spike, AD-002)

@implementation Nuntis {
    NuntisImpl *_impl;
}

- (instancetype)init {
    if (self = [super init]) {
        _impl = [NuntisImpl new];
    }
    return self;
}

- (NSNumber *)multiply:(double)a b:(double)b {
    return [_impl multiply:a b:b];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<facebook::react::NativeNuntisSpecJSI>(params);
}

+ (NSString *)moduleName
{
  return @"Nuntis";
}

@end
