import UserNotifications

/// Rich-push attachment helper for the Notti Notification Service Extension.
///
/// Deliberately has ZERO dependency on React/TurboModule — a
/// `UNNotificationServiceExtension` target is a separate sandboxed process the
/// OS launches directly from APNs; it never runs the RN runtime, so linking
/// this against `React-Core` would break the extension's build. This file
/// ships in its own Podspec subspec (`Notti/NotificationServiceExtension`)
/// for exactly that reason — see `docs/adr/002-...md`.
///
/// The integrator's own `NotificationService.swift` (generated by Xcode's
/// "Notification Service Extension" template) is reduced to a one-line
/// forwarding call, mirroring `OneSignalExtension.didReceiveNotificationExtensionRequest`:
///
/// ```swift
/// override func didReceive(
///   _ request: UNNotificationRequest,
///   withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void
/// ) {
///   NottiNotificationServiceExtension.didReceive(request, withContentHandler: contentHandler)
/// }
///
/// override func serviceExtensionTimeWillExpire() {
///   NottiNotificationServiceExtension.serviceExtensionTimeWillExpire(
///     for: bestAttemptContent, withContentHandler: contentHandler
///   )
/// }
/// ```
public final class NottiNotificationServiceExtension {

  /// Payload key the Notti backend sets alongside `mutable-content: 1` when a
  /// push carries a rich attachment. Sibling of `aps`, same convention as the
  /// integrator's own custom `data` fields (see ADR-002).
  private static let attachmentURLKey = "image"

  private init() {}

  public static func didReceive(
    _ request: UNNotificationRequest,
    withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void
  ) {
    guard let content = request.content.mutableCopy() as? UNMutableNotificationContent else {
      contentHandler(request.content)
      return
    }

    guard
      let urlString = request.content.userInfo[attachmentURLKey] as? String,
      let url = URL(string: urlString)
    else {
      contentHandler(content)
      return
    }

    downloadAttachment(from: url) { attachment in
      if let attachment {
        content.attachments = [attachment]
      }
      contentHandler(content)
    }
  }

  /// Apple's last-chance callback when `didReceive` didn't call its content
  /// handler before the ~30s NSE budget runs out. Must present *something* —
  /// falling back to the original (attachment-less) content is the documented
  /// pattern, same as OneSignal's `bestAttemptContent` fallback.
  public static func serviceExtensionTimeWillExpire(
    for request: UNNotificationRequest,
    contentHandler: @escaping (UNNotificationContent) -> Void
  ) {
    contentHandler(request.content)
  }

  private static func downloadAttachment(
    from url: URL,
    completion: @escaping (UNNotificationAttachment?) -> Void
  ) {
    let task = URLSession.shared.downloadTask(with: url) { location, response, error in
      guard let location, error == nil else {
        completion(nil)
        return
      }

      let destinationURL = FileManager.default.temporaryDirectory
        .appendingPathComponent(UUID().uuidString)
        .appendingPathExtension(fileExtension(for: response, fallbackFrom: url))

      do {
        try FileManager.default.moveItem(at: location, to: destinationURL)
        let attachment = try UNNotificationAttachment(
          identifier: UUID().uuidString, url: destinationURL, options: nil
        )
        completion(attachment)
      } catch {
        completion(nil)
      }
    }
    task.resume()
  }

  /// `UNNotificationAttachment` infers its UTType from the destination file's
  /// *extension*, not its content — a download landing at a temp path with no
  /// extension (common for `URLSession` temp files) would otherwise be
  /// rejected. Prefers the response's MIME type over the URL's own extension
  /// since a CDN/redirect can serve `image/jpeg` from a path with none.
  static func fileExtension(for response: URLResponse?, fallbackFrom url: URL) -> String {
    if let mimeType = response?.mimeType, let mapped = fileExtension(forMimeType: mimeType) {
      return mapped
    }
    let pathExtension = url.pathExtension
    return pathExtension.isEmpty ? "jpg" : pathExtension
  }

  private static func fileExtension(forMimeType mimeType: String) -> String? {
    switch mimeType {
    case "image/jpeg": return "jpg"
    case "image/png": return "png"
    case "image/gif": return "gif"
    case "video/mp4": return "mp4"
    case "audio/mpeg": return "mp3"
    default: return nil
    }
  }
}
